Repository highlight-ing/highlight-chat-frontend, pull requests merged in 2024-09, with the labels that each got.

#210 feat: track user id for recent convos
  src/hooks/usePromptApps.ts
  src/utils/prompts.ts
Labels: enhancement

#217 Feat filter recent usage for personal prompts
  src/app/api/v1/user/prompts/route.ts
  src/hooks/usePromptApps.ts
  src/presentations/modals/PinPromptModal.tsx
  src/presentations/modals/UnpinPromptModal.tsx
  src/utils/prompts.ts
Labels: enhancement

#223 fix-tags-overflow
  src/components/TrendingPrompts/TrendingPrompts.tsx
  src/components/TrendingPrompts/trending-prompts.module.scss
Labels: bug

#225 fix-fix-trending-prompts
  src/components/TrendingPrompts/trending-prompts.module.scss
Labels: bug

#257 Feature/hig 197 fix what happened at 351
  src/hooks/useSubmitQuery.ts
  src/utils/streamParser.ts
Labels: bug

#266 Feature/hig 111 sharing fixes
  src/components/Navigation/TopBar.tsx
  src/components/Navigation/top-bar.module.scss
  src/components/ShareModal/ShareModal.tsx
  src/hooks/useShareConversation.ts
Labels: bug

#267 chore: trending prompt will open preview
  src/components/TrendingPrompts/TrendingPrompts.tsx
  src/components/TrendingPrompts/trending-prompts.module.scss
Labels: enhancement

#297 chore: pin cta on trending actions and better description on Pin Acti…
  src/components/TrendingPrompts/TrendingPrompts.tsx
  src/presentations/modals/PinPromptModal.tsx
Labels: enhancement

#312 fix: trending prompts preview view trigger
  .gitignore
  dump.rdb
  src/components/TrendingPrompts/TrendingPrompts.tsx
Labels: bug

#305 Conversation attachment picker
  src/components/Attachment.tsx
  src/components/AttachmentPicker/AttachmentPicker.tsx
  src/components/AttachmentPicker/attachment-picker.module.scss
  src/components/AttachmentsButton/AttachmentsButton.tsx
  src/components/ConversationAttachmentPicker.tsx/ConversationAttachmentPicker.tsx
  src/components/Conversations/AudioTranscriptionComponent.tsx
  src/components/Conversations/ConversationDisplay.tsx
  src/components/Conversations/ConversationEntry.tsx
  src/components/Conversations/ConversationSimple.tsx
  src/components/ScreenshotAttachmentPicker/ScrenshotAttachmentPicker.tsx
  src/context/ConversationContext.tsx
  src/utils/conversations.ts
  src/utils/string.ts
Labels: DO NOT MERGE
